customerorders:
  outputs:
    dev:
      dataset: snapshot_customerorders
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: oauth
      priority: interactive
      project: datastreamdemo-412310
      threads: 1
      type: bigquery
  target: dev